spring.datasource.url=jdbc:mysql://tramway.proxy.rlwy.net:23402/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=AfKLViNmcVaPnZwngOcZWKvsmvJsVhHa

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
